implement tsinfo messages for retrieving timestamping capabilities
rust-netlink/ethtool pull request #5
Opened 2022-10-25 09:56 UTC by alworx

Add [tsinfo](https://github.com/torvalds/linux/blob/8bb7eca972ad531c9b149c0a51ab43a417385813/include/uapi/linux/ethtool_netlink.h#L432) messages for retrieving timestamping capabilites of network interfaces. Basically a copycat operation from `link_mode` :)

Extract bitset parsing utils to a separate files (as they are now used by `link_mode` and `tsinfo` modules) and add a network interface filter to the example (i can remove this or add to the other examples as well?).

2022-10-27 09:16 UTC, wllenyj commented on src/bitset_util.rs
> +use anyhow::Context;
License ?

2023-01-29 10:20 UTC, cathay4t requested changes
* Please squash into single commit.
 * Please use add `Signed-off-by: Name <email@example.com>` to commits or use `git commit --signoff`.

2023-02-20 14:22 UTC, alworx commented
> * Please squash into single commit.
> * Please use add `Signed-off-by: Name <email@example.com>` to commits or use `git commit --signoff`.
> * Rebase to latest.

All set!

2023-02-21 03:27 UTC, cathay4t approved these changes
Manually tested in my VM, the example works well comparing to `ethtool -T` command. Thanks for the contribution!

2023-02-21 03:27 UTC, merged

2023-02-21 03:27 UTC, cathay4t commented
Merged!